In [108]:
import numpy as np
import numpy.typing as npt
from collections.abc import Callable
import pandas as pd

In [109]:
znaki_wz: npt.NDArray[np.int8] = np.array([[
    [1, 0, 0, 1],
    [1, 0, 0, 1],
    [1, 0, 0, 1],
    [1, 0, 0, 1],
    [1, 0, 0, 1],
], [
    [1, 0, 0, 0],
    [1, 0, 0, 0],
    [0, 1, 1, 0],
    [1, 0, 0, 0],
    [1, 0, 0, 0],
], [
    [0, 0, 0, 1],
    [0, 0, 0, 1],
    [1, 1, 1, 1],
    [0, 0, 0, 1],
    [0, 0, 0, 1],
]])
znak_test: npt.NDArray[np.int8] = np.array([
    [0, 0, 0, 0],
    [0, 0, 0, 1],
    [1, 1, 1, 1],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
])

In [110]:
def metryka_euklidesowa(pa: tuple[float, float], pb: tuple[float, float]):
    return np.sqrt((pa[0] - pb[0])**2 + (pa[1] - pb[1])**2)

def metryka_manhattan(pa: tuple[float, float], pb: tuple[float, float]):
    return abs(pa[0] - pb[0]) + abs(pa[1] - pb[1])

In [111]:
def algorytm_zachlannego_dopasowania(
        znak1: npt.NDArray[np.int8],
        znak2: npt.NDArray[np.int8],
        metryka_odleglosci: Callable
) -> float:
    # 1.	miara := 0
    miara = 0
    bitmapa_wynikowa = np.zeros((len(znak1), len(znak1[0])))
    # 2.	Wykonaj pętlę dla każdego czarnego punktu o pozycji (pay, pax) w BA
    for pay in range(len(znak1)):
        for pax in range(len(znak1[0])):
            if znak1[pay][pax] == 0:
                continue
            # 1.	odl_min = + nieskończoność
            odl_min = np.inf
            # 2.	Wykonaj pętlę dla każdego czarnego punktu o pozycji (pby, pbx) w BB
            for pby in range(len(znak2)):
                for pbx in range(len(znak2[0])):
                    if znak2[pby][pbx] == 0:
                        continue
                    # 1.	 odl_akt := odległość między punktami (pay, pax) a (pby, pbx)
                    odl_akt = metryka_odleglosci((pbx, pby), (pax, pay))
                    # 2.	 odl_min := min{odl_min, odl_akt}
                    if odl_akt < odl_min:
                        odl_min = odl_akt
            bitmapa_wynikowa[pay, pax] = f"{odl_min:.2f}"
            # 3.	miara := miara +  odl_min
            miara += odl_min
    print(pd.DataFrame(bitmapa_wynikowa).values)
    print(miara)
    return miara

# Raport

## Niepodobieństwo obustronne pomiędzy znakiem testowym a znakiem wzorcowym 1.,
metryka Manhattan

In [112]:
miara1 = algorytm_zachlannego_dopasowania(znaki_wz[0], znak_test, metryka_manhattan)
miara2 = algorytm_zachlannego_dopasowania(znak_test, znaki_wz[0], metryka_manhattan)
miara = -miara1 - miara2
miara

[[2. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 1.]
 [2. 0. 0. 2.]]
10
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2


-12

## Niepodobieństwo obustronne pomiędzy znakiem testowym a znakiem wzorcowym 2., metryka Manhattan;

In [113]:
miara1 = algorytm_zachlannego_dopasowania(znaki_wz[1], znak_test, metryka_manhattan)
miara2 = algorytm_zachlannego_dopasowania(znak_test, znaki_wz[1], metryka_manhattan)
miara = -miara1 - miara2
miara

[[2. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [2. 0. 0. 0.]]
6
[[0. 0. 0. 0.]
 [0. 0. 0. 2.]
 [1. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
4


-10

## Niepodobieństwo obustronne pomiędzy znakiem testowym a znakiem wzorcowym 3., metryka Manhattan;

In [114]:
miara1 = algorytm_zachlannego_dopasowania(znaki_wz[2], znak_test, metryka_manhattan)
miara2 = algorytm_zachlannego_dopasowania(znak_test, znaki_wz[2], metryka_manhattan)
miara = -miara1 - miara2
miara

[[0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 2.]]
4
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
0


-4

## Niepodobieństwo obustronne pomiędzy znakiem testowym a znakiem wzorcowym 1., metryka euklidesowa;

In [115]:
miara1 = algorytm_zachlannego_dopasowania(znaki_wz[0], znak_test, metryka_euklidesowa)
miara2 = algorytm_zachlannego_dopasowania(znak_test, znaki_wz[0], metryka_euklidesowa)
miara = -miara1 - miara2
miara

[[2. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 1.]
 [2. 0. 0. 2.]]
10.0
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2.0


np.float64(-12.0)

## Niepodobieństwo obustronne pomiędzy znakiem testowym a znakiem wzorcowym 2., metryka euklidesowa;

In [116]:
miara1 = algorytm_zachlannego_dopasowania(znaki_wz[1], znak_test, metryka_euklidesowa)
miara2 = algorytm_zachlannego_dopasowania(znak_test, znaki_wz[1], metryka_euklidesowa)
miara = -miara1 - miara2
miara

[[2. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [2. 0. 0. 0.]]
6.0
[[0.   0.   0.   0.  ]
 [0.   0.   0.   1.41]
 [1.   0.   0.   1.  ]
 [0.   0.   0.   0.  ]
 [0.   0.   0.   0.  ]]
3.414213562373095


np.float64(-9.414213562373096)

## Niepodobieństwo obustronne pomiędzy znakiem testowym a znakiem wzorcowym 3., metryka euklidesowa

In [117]:
miara1 = algorytm_zachlannego_dopasowania(znaki_wz[2], znak_test, metryka_euklidesowa)
miara2 = algorytm_zachlannego_dopasowania(znak_test, znaki_wz[2], metryka_euklidesowa)
miara = -miara1 - miara2
miara

[[0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 2.]]
4.0
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
0.0


np.float64(-4.0)